### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by WYHBlueAlgae** [RockyChing/the_expanse#2]
感谢翻译！请问是在从后往前翻吗，目前进展如何（刚看完小说前两部发现后面都没有中译版了

**Comment by RockyChing** [comment]
> 感谢翻译！请问是在从后往前翻吗，目前进展如何（刚看完小说前两部发现后面都没有中译版了

1.计划中只打算翻译最后大结局一部（第9部）。
2.其他翻着玩了，没计划。
